import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import LandingSection from "../app/components/LandingSection";
import ProductsSection from "../app/components/ProductsSection";
import { Producto } from "../app/ts/producto.interface";

const Home = ({productos} : { productos : Producto[]}) => {
  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingSection />
      <ProductsSection productos={productos}/>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const productos = await fetch(
    "https://fakestoreapi.com/products"
  ).then((res) => res.json());

  return {
    props: {
      productos: productos,
    },
  };
};

